version: '3'

services:
  app:
    image: busybox
    command: sh -c 'sleep 1; printf "%016384dHello\n" 0'
    logging:
      driver: fluentd
      options:
        fluentd-async: 'true'
  fluent-bit:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 24224:24224
    command: timeout 30 /fluent-bit/bin/fluent-bit --quiet -i forward -o stdout